# Dependencies
markdown:	kramdown
# Permalinks
permalink:

# Setup
title:            Sean Green
tagline:          'Computer Engineer'
description:      'My Stomping Grounds.'
url:              https://www.linkedin.com/in/sean-green-aa42b4113/
baseurl:          
commentsystem:    google
disqus:           example

author:
  name:           Sean Green
  url:            https://sgreen03.github.io/

paginate:         5

# Custom vars
icon:             /assets/images/1186315_10202030959997552_1439623194_n.jpg
cover:            /assets/images/25.jpg

social:
  - icon:         twitter
    url:          https://twitter.com/IronmanGreen
    desc:         Follow me on twitter

  - icon:         github
    url:          https://github.com/sgreen03
    desc:         View my github page
    
  - icon:         facebook
    url:          https://www.facebook.com/sean.green.3139
    desc:         Add me on Facebook

  - icon:         linkedin
    url:          https://www.linkedin.com/in/sean-green-aa42b4113/
    desc:         Add me on LinkedIn


menu:
  - title:        Home
    url:          /

  - title:        About
    url:          /about
    
  - title:        Resume
    url:          /SeanGreenResume.pdf
    
  - title:        Contact Me
    url:          /ContactMe
    

copyright:
  author:         Sean Green
  url:            https://sgreen03.github.io/
  type_title:     Some rights reserved
  type_url:       http://creativecommons.org/licenses/by-nc/2.5

parallax:         false

# Google Analytics (add the UA Code, e.g.: UA-xxxxxxxx-1)
google_analytics:  

# Default Theme Color for Chrome on Android Lollipop (Use RGB ColorCode without `#`, e.g.: `db5945`)
theme_color:       7E9576
